### ISSUE TITLE
Unknown behaviour when two images have the same name

### ISSUE THREAD

**Issue by Holmistr** [jenkinsci/openstack-cloud-plugin#119]
Hi,
I (basically accidentally) came across a situation, when I created two images with the same name in OpenStack and in Jenkins I was using specifying by name. The problem is that I noticed it by luck, hence it could be quite a hard-to-find issue. Perhaps the plugin could check if there are some name collisions. Or at least document, how the plugin would behave.

**Comment by olivergondza** [comment]
Right, it picks one image at random if the name is the same. This should be documented better.

**Comment by pjdarton** [comment]
Personally, I'm not a fan of "random" - I lost most of a day to this behavior :-/

I can think of two better options when there are multiple IDs matching a given name:
1) Throw (and log) an error and refuse to use this template
2) Log a warning about the conflict and use a deterministic method for choosing one of them, e.g. "the oldest".
...and, either way, the UI code should warn the user if we have multiple IDs for the name that the user has selected.

If we can agree on the "right" approach here, I'm willing to have a go at implementing it :-)

**Comment by Holmistr** [comment]
@pjdarton I would vote for option 2 :)

**Comment by olivergondza** [comment]
I do not like #1 either. I am up for #2, perhaps defaulting for the newest.

---

To elaborate on my use-case: I generate snapshots later to be launched by the plugin. So occasionally, there can be multiple such images and plugin should be able to provision without failure in such cases.

**Comment by pjdarton** [comment]
My use-case is similar - we're also intending to generate all our images (or volume-snapshots in my case) programatically and then have Jenkins start using those in place of the old ones.

OK, I'll see if I can implement a "Warn, and use newest" when we've got multiple things of the same name.
FYI when I've got support for volume-snapshot based VMs fully operational, I'll ensure that it uses the same decision making here too.

The downside of just logging a warning is that most users will never see the warning, but I can't think of any alternative to that right now.  Hopefully any Jenkins-admin folks will go and look at the cloud settings when things aren't working well and then they'd see a warning from the Jelly descriptor validation code telling them.

So, just to be clear on what we're proposing here:
1) In the UI, users will continue to be given lists of names with duplicates removed.
2) In the UI, if a user selects a name that has multiple objects with that name, we warn the user.
3) In the provisioning code, if we look up something by name and get multiple answers, we should choose the newest one and log a warning saying that we're choosing <ID> but there are <N> things named <NAME>.

At a guess, that'll mean that...
the Openstack.java code's "list everything" methods that currently filter out duplicate names should probably stop doing that, but return lists sorted by name & newest.
the SlaveOptionsDescriptor code will have to make a unique sorted list of names itself with which to populate selection lists.
the Openstack.java "find ID given name-or-Id" methods should return a list of ids instead of just id-or-null.
the provisioning code will have to cope with getting a list<string> instead of id-or-null, and warn if the list.size()>1.

**Comment by olivergondza** [comment]
Exactly.

**Comment by pjdarton** [comment]
The reason that I am interested in being able to boot from a volume snapshot is because the people who administer "my" OpenStack instances believe that they cannot enforce disk-usage quotas on a per-project basis if we use images, but that they are able to do so if we use volume snapshots.
Their reasoning is that "glance" (the subsystem responsible for images) does not allow different projects to have different quota limits (you can set a quota limit, but that limit is applied to all projects - see http://docs.openstack.org/ops-guide/ops-quotas.html), whereas "cinder" (the subsystem responsible for volumes) does allow different projects to have different quotas set (see http://docs.openstack.org/admin-guide/cli-cinder-quotas.html).
If you know of a way of setting *different* disk-usage quotas for different projects within the same OpenStack system then please let me know - if I can convince my OpenStack admins that they can allow me to use images, it will greatly simplify my plugin work (i.e. cleaner code).

**Comment by olivergondza** [comment]
Fair enough. Let's do this.

**Comment by pjdarton** [comment]
Code changes have been made in https://github.com/jenkinsci/openstack-cloud-plugin/pull/136 and are ready for merge now.

These changes add support for volume-snapshots (which I need) *and* also make the plugin's behavior deterministic (not random!) when multiple images (or volume-snapshots) match the name chosen by the user.
There's a build of this code at https://jenkins.ci.cloudbees.com/job/plugins/job/openstack-cloud-plugin/312/ so please give it a try and let me know if the "choose the latest image with the given name" functionality is doing what you expect/want.

**Comment by pjdarton** [comment]
@Holmistr The current release (2.29) includes my PR #136 which included a fix for this
 - the code now warns the user if a Image/VolumeSnapshot name is ambiguous
 - the code now always chooses the most recent Image/VolumeSnapshot if there's more than one of the same name...
 - ... and logs a warning that it had to make this decision.

I think we can close this issue - do you agree?

**Comment by Holmistr** [comment]
Sounds great, thanks @pjdarton ! :)
