### ISSUE TITLE
Allow configuration of 'Exclude matrix parents from running on this slave.' for a template

### ISSUE THREAD

**Issue by winklerm** [jenkinsci/openstack-cloud-plugin#132]
The Cloud template configuration currently lacks options for the _Node properties_ (as we know from the Jenkins node configuration). 

We are particularly interested in '_Exclude matrix parents from running on this slave._' option because we need to avoid running matrix parents on dynamically provisioned Windows slaves. 

Adding the other configuration properties would be nice to have but not necessary for us at the moment.

**Comment by rhatlapa** [comment]
I would welcome that option as well.

**Comment by zebrik** [comment]
#MeToo :-)

**Comment by pjdarton** [comment]
Personally, I find that telling matrix projects to restrict where they run to just "master" works fine.
...and then you control where the matrix "real work" happens using a (or more than one) matrix axis.

**Comment by pjdarton** [comment]
Very true - I agree that it would be better if the end user didn't have to do any configuration to make it "just work".

... so ... FYI the vSphere plugin has [code](https://github.com/jenkinsci/vsphere-cloud-plugin/blob/vsphere-cloud-2.18/src/main/java/org/jenkinsci/plugins/vSphereCloudSlave.java#L254) in `vSphereCloudSlave.java`'s `canTake` method that says:
```
    @Override
    public CauseOfBlockage canTake(BuildableItem buildItem) {
...
        if(buildItem.task instanceof Queue.FlyweightTask) {
            return CauseOfBlockage.fromMessage(Messages._vSphereCloudSlave_BlockageReason_NoFlyweightTasks());
        }
...
        return super.canTake(buildItem);
    }
```
where `Messages._vSphereCloudSlave_BlockageReason_NoFlyweightTasks()` is
```
    public static Localizable _vSphereCloudSlave_BlockageReason_NoFlyweightTasks() {
        return new Localizable(holder, "vSphereCloudSlave.BlockageReason.NoFlyweightTasks");
    }
```
and the associated `Messages.properties` file has the [line](https://github.com/jenkinsci/vsphere-cloud-plugin/blob/vsphere-cloud-2.18/src/main/resources/org/jenkinsci/plugins/Messages.properties#L2):
```
vSphereCloudSlave.BlockageReason.NoFlyweightTasks=Don't run FlyweightTasks on vSphere nodes as they can be terminated.
```

My understanding of this code is that it is intended to prevent "flyweight" tasks (such as the matrix "parent" job) from running on the node.
A "flyweight" task does not consume an executor, does not make a node "non-idle" and does not affect the retention of a cloud-provisioned node, so _without_ this code, it's possible for a flyweight task to be running on a cloud-provisioned node right at the time when that cloud-provisioned node is being destroyed, thus breaking the flyweight task (e.g. a matrix build's parent job).

So, what we could do is use the same technique that's used by the vSphere plugin so that the OpenStack slaves don't accept flyweight tasks and then this should solve the problem.
Implementing node properties would be another option (and has its own advantages), but then users would have to add that node property to all OpenStack templates themselves in order to prevent matrix parent jobs breaking.

Disclaimer: This code in the vSphere-plugin was written before I became involved in that plugin - I do not have any proof that it's achieving these results.  However, the code looks plausible to me.

**Comment by olivergondza** [comment]
@pjdarton, yes that is a straightforward way to do so. Just a minor correction, "flyweight tasks" have special "one off" executors created for the stave it is running on and that prevent the computer to be considered idle. see https://github.com/jenkinsci/jenkins/blob/a17bd1cbfa674f4050bbf5dc1ca7d4721d7e9302/core/src/main/java/hudson/model/Computer.java#L1020-L1027.

So the effect here is the openstack machine is retained for the whole time flyweight task is running.

**Comment by pjdarton** [comment]
OK, so it doesn't make it "idle" ... but I'm pretty sure (from experience _before_ I set all my matrix jobs to be restricted to "master") that there's enough race conditions in this area that a node's retention strategy  (e.g. for a single-use node) and/or the "single use slave" flag (on a build) may decide to terminate a node _regardless_ of the presence of flyweight tasks on the node.

i.e. the "one true path to happiness" is to make sure that flyweight tasks do not run on cloud-provisioned slaves.

**Comment by olivergondza** [comment]
Agreed

**Comment by olivergondza** [comment]
@pjdarton, have just contributed an improvement to this in 2.48.
