### ISSUE TITLE
openstack-cloud-plugin 2.17 does not retry after failed authentication

### ISSUE THREAD

**Issue by zxiiro** [jenkinsci/openstack-cloud-plugin#137]
When we upgraded openstack-cloud-plugin to 2.17 (from 2.11) we found that our slaves are no longer getting attached. In the older version 2.11 it seems that the system retries the connection a few times before giving up so we're able to connect eventually but in the newer 2.17 version of the plugin it appears to give up after only a single attempt.

Anyway we can activate the old behaviour with the new plugin? Our slaves typically fail the first few authentications attempts before successfully connecting so the new behaviour is breaking us.

I have not yet attempted any versions between 2.17 and 2.11 so cannot yet confirm when the issue was introduced.

`ERROR: Server rejected the 1 private key(s) for jenkins (credentialId:test-credential/method:publickey)
[01/26/17 17:50:49] [SSH] Authentication failed.
hudson.AbortException: Authentication failed.
at hudson.plugins.sshslaves.SSHLauncher.openConnection(SSHLauncher.java:1231)
at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:724)
at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:719)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
[01/26/17 17:50:49] Launch failed - cleaning up connection`

**Comment by zxiiro** [comment]
After some more testing I can confirm that 2.15 version introduced the regression. If I revert back to 2.14 ssh connection works as expected and openstack plugin attempts to connect multiple times on ssh auth error.

**Comment by zxiiro** [comment]
After doing a git bisect I can confirm that the issue we are seeing was introduced by change ce78c0bb5587331ce3b33b489ce8e10d5572d2f5

Any way we can revert this back as this issue is preventing us from using the latest version of openstack plugin.

**Comment by olivergondza** [comment]
@zxiiro 
The `ssh-slaves` plugin is not expected to retry failed authentication - only failed connection attempt. I presume the problem you are observing is caused by ssh connection attempt arriving between ssh setup and user/auth configuration so authentication attempt is rejected. The fix you suggest to revert corrects something I really do not want to reintroduce. I see 3 ways to go here:

- You update your provisioning routines[1] so ssh would fail with one of [2] until it is fully configured. Requires `ssh-slaves` release -  I intend to do that today.
- We update `ssh-slaves` plugin to retry authentication as well - this only makes sense for provisioning so I am not confident people will like it there.
- We update `openstack-cloud` to bring the connection retrying loop back (without the downsides of https://github.com/jenkinsci/openstack-cloud-plugin/commit/ce78c0bb5587331ce3b33b489ce8e10d5572d2f5) that will be able to retry even when `ssh-slaves` does not - authentication failure.

[1] https://github.com/jenkinsci/acceptance-test-harness/blob/master/src/test/resources/openstack_plugin/cloud-init#L16-L24
[2] https://github.com/jenkinsci/ssh-slaves-plugin/pull/41/files#diff-80fc627a638d10d5056a52e20a13d8cbR157

**Comment by tykeal** [comment]
We don't provision a jenkins user until the very end of the cloud-init so that we guarantee that all start-up routines have completed.

As such, since SSH comes up _before_ cloud-init has finished and your removal of the auth retry loop we end up failing a minion connection 19/20 times (we do occasionally get lucky that the init completes before auth is tried). Since the OpenStack Cloud plugin doesn't presently support phone-home we can't even use that feature of cloud-init!

We don't want to be using JNLP for our minion startup as it needlessly complicates our initialization. So some sort of retry-loop needs to be added back somewhere.

**Comment by olivergondza** [comment]
I agree that recovering from auth failure as well is desirable.

**Comment by zxiiro** [comment]
@olivergondza I think updating openstack-cloud plugin might be the best course of action. I've tried poking at this from a few angles but I'm stuck. I'm not entirely sure how to implement a loop that specifically checks for the SSH failure. The old code just checked if the slave is offline which I'm believe is what you do not want to reintroduce. Happy to help however I can but have to admit I'm not very familiar with how these things connect with each other.

**Comment by olivergondza** [comment]
> The old code just checked if the slave is offline which I'm believe is what you do not want to reintroduce.

Not really. What I do not want to reintroduce is waiting for it to come up in `Cloud#provision` and adding it to Jenkins prematurely. I dare to say this can be rather straightforward fix in `JCloudsLauncher#launch` looping waiting for the node to be up. One thing to figure out there would be ho to propagate the start of the boot so we can implement timeouts properly (`startTimeout`).

**Comment by zxiiro** [comment]
Probably not the best solution by my attempt  with #138

**Comment by zxiiro** [comment]
Thanks I've deployed @olivergondza 's fix to one of our systems. Will report back if we have any issues however things look good so far in our initial testing.
