### ISSUE TITLE
Tables to Divs migration

### ISSUE THREAD

**Issue by tsr-caubry** [jenkinsci/openstack-cloud-plugin#312]
Newer versions of Jenkins now use divs instead of tabs for the UI, the plugin seems broken with these versions.

c.f. [https://www.jenkins.io/blog/2020/11/10/major-changes-in-weekly-releases/](https://www.jenkins.io/blog/2020/11/10/major-changes-in-weekly-releases/)

**Comment by matttbe** [comment]
Hello,

I confirm that I can no longer access the "Template" menu.

This looks very similar to [JENKINS-64357](https://issues.jenkins.io/browse/JENKINS-64357?filter=22840&jql=labels%20in%20(tables-to-divs-regression)) ticket. Do you prefer if a bug report is opened there with `tables-to-divs-regression` label?

Note that the bug in vsphere-cloud-plugin has been fixed in: https://github.com/jenkinsci/vsphere-cloud-plugin/pull/126

BTW, thank you for developing and maintaining this nice plugin! :)

**Comment by olivergondza** [comment]
Thanks for the report, guys! I have filed https://issues.jenkins.io/browse/JENKINS-65157 to indicate the plugin is not ready jet.
