### ISSUE TITLE
Instance cap is ignored if multiple cloud instances are set and set to default instead (10)

### ISSUE THREAD

**Issue by kpiwko** [jenkinsci/openstack-cloud-plugin#65]
I have two instance options, say one for rhel7 and the other for fedora22. 

I have set limit of instance to 15 in general setup, however the second instance option is limited by 10. I believe it is due to https://github.com/jenkinsci/openstack-cloud-plugin/blob/master/src/main/java/jenkins/plugins/openstack/compute/SlaveOptions.java#L222 and default option value of 10.

**Comment by olivergondza** [comment]
The template level restriction is not implemented yet, thanks for pointing that out[1]. Currently, it should allow as many as the global _# of instances_ irregardless of the template or template setting.

If that is not what you observe. What are the settings, what is the observed vs expected behaviour?

[1] https://github.com/jenkinsci/openstack-cloud-plugin/blob/master/src/main/java/jenkins/plugins/openstack/compute/JCloudsCloud.java#L196

**Comment by kpiwko** [comment]
I have global updated to 15. As I've added another template, it seems there are only 10 instances allowed for that template. I didn't have any instance of original template running at that time.

Globals work fine if there is just one template. Is that clear enough or do you want me to attach screenshot or such?

**Comment by olivergondza** [comment]
@kpiwko, you are right, the code is all wrong as it does not allow it to be configured to anything higher than 10 (plugin default).
