### ISSUE TITLE
Incorrect number of available slaves displayed in job config

### ISSUE THREAD

**Issue by ppitonak** [jenkinsci/openstack-cloud-plugin#69]
When I select some label in "Restrict where this project can be run" in job configuration, it shows one slave more than actual number (e.g. 1 when no slaves exist, 2 when only 1 slave is running in OpenStack).

**Comment by olivergondza** [comment]
This is a bug in Jenkins core (fixed in [1.626](https://github.com/jenkinsci/jenkins/commit/647e82f9c4792cadf30fa65621d8c147414d8869)) that computes the the number of machines as `# of slaves in label + # of clouds able to provision that label` (so I guess you have 1 cloud configured in you instance). This plugin can not do anything about it I am afraid.
