### ISSUE TITLE
Add functionality to clean stranded OpenStack floating IPs

### ISSUE THREAD

**Issue by mvinkler** [jenkinsci/openstack-cloud-plugin#84]
Right now, the floating IP remains allocated when the instance is terminated. 

Some additional info:
https://mojo.redhat.com/docs/DOC-988410
https://code.engineering.redhat.com/gerrit/gitweb?p=ci-ops-central.git;a=blob;f=bootstrap/run_janitor.sh
https://code.engineering.redhat.com/gerrit/gitweb?p=ci-ops-projex.git;a=blob;f=jobs/service_jobs.yaml

**Comment by olivergondza** [comment]
Reducing the scope to FIPs as VM are tracked already as https://github.com/jenkinsci/openstack-cloud-plugin/issues/60.

**Comment by Holmistr** [comment]
Hi @olivergondza , is there any progress on this issue? It's a really annoying bug, we've just experienced jobs being waiting just because we didn't notice that the floating IPs quota was exceeded :( ... I looked into it, but to be honest I didn't understand it very well, hence passing it back to you.

**Comment by olivergondza** [comment]
I am in the process of verifying stranded instance cleanup to go to the next release. The nasty thing about IPs (compared to VMs) is we can not tag it in metadata so it hard to say why it was allocated and who did it. So I intend to implement this in delete-all-fips-unused-for-a-period-of-time fashion.

**Comment by Holmistr** [comment]
@olivergondza  I see. In that case your approach sounds good, can't wait to see it implemented :)

**Comment by vjuranek** [comment]
@olivergondza I quickly checked the code - do you have an idea why [Openstack#destroyServer)()](https://github.com/jenkinsci/openstack-cloud-plugin/blob/master/src/main/java/jenkins/plugins/openstack/compute/internal/Openstack.java#L289) doesn't wok properly? The code LGTM ... or this method is not called at all for some reason during termination of slave?

**Comment by olivergondza** [comment]
@vjuranek, It has been reworked since [2.17](https://github.com/jenkinsci/openstack-cloud-plugin/blob/e16a76de109c044fbc7c902b693c2fa3cbf74226/src/main/java/jenkins/plugins/openstack/compute/internal/Openstack.java#L263) significantly. One of the ways to for server or IP to leak was openstack refused to delete it successfully on 10 attempts. My hopes are this will get better with resource disposer.
