### ISSUE TITLE
Job not executed on the node

### ISSUE THREAD

**Issue by pmithrandir** [jenkinsci/openstack-cloud-plugin#92]
Hello,

When doing the job, the node is deployed, but the job is not executed on it, but on another node available.

Any idea why ?

Pierre
Example : 
to run a job with label XXX, I need a slave A up with XXX, and then it will deploy the cloud node B with label XXX.
It will then execute the job on A, in place of B, then immediately turn off B.

I don't think it's the expected result.

**Comment by olivergondza** [comment]
I do not think I follow. What is the expected vs. actual behavior?

**Comment by zxiiro** [comment]
@pmithrandir do you have the same label applied to both your static slave as well as your dynamic slave managed by openstack?

If so Jenkins will always run jobs against available slaves with the assigned label if one is already available. What I'm guessing is happening is because you have a static slave assigned with the same label as the openstack-cloud-plugin managed dynamic slave when the job is queued, openstack-cloud-plugin detects that there is no dynamic slaves available to process the job queue so starts spinning up a new slave. In that time Jenkins sends the job to the available static slave and starts running the job.

I would recommend you assign different labels to your static vs dynamically assigned slaves.

**Comment by pmithrandir** [comment]
Hello,

I have tried to apply a specific label to my openstack node and to require it in my job.
When running a job, I get the "pending" state, where jenkins afil to identify a compatible node. I don't see any creation in openstack then.

Actually, I don't think the openstack node are build outside the jobs, jobs that couldn't run because no compatible node are found. Is there some setup to change to activate that option ?

We are really interested to use it(and we have already some fix to provide regarding proxy) but today we fail to activate the most basic function of the plugin.

Same, node are actually destroyed right inside the build, and not 10 or 30 minutes later.

Pierre

**Comment by zxiiro** [comment]
This is how we use openstack-cloud-plugin in our organisation. You can see our setup here:

https://jenkins.opendaylight.org/releng/

1. In Manage Jenkins > Configure System configure openstack cloud and a build slave and assign it a unique label
2. Modify a build job to restrict it to run only on the assigned label from 1
3. Add a build to the queue

At this point the job should sit in the queue for about a minute and during that time OpenStack should start spinning up the slave assigned to the label in 1 automatically depending on your setup it may take a few minutes to fully spin up.

4. Slave attaches to Jenkins
5. Job runs on the attached slave

For troubleshooting you can check the Jenkins logs on the server side for any exceptions in case of incorrect configuration.

**Comment by pmithrandir** [comment]
wrong report... sorry.
I was not using te system the right way.

After getting some explanation, especially the fact that slaves were created on demand without need to change job openstack section  that the pending was actually normal, It's now working ok.
I'm closing it.
Sorry,
Pierre

**Comment by olivergondza** [comment]
Thanks @zxiiro! Please let me know if you feel the documentation/wiki is hard to grasp for newcomers.

**Comment by zxiiro** [comment]
@olivergondza is the wiki the only source of documentation for this plugin? I'll see if I can find some time to improve it.
